---
- hosts: all
  gather_facts: yes

  vars:
    APP_PATH: /var/apps/chute-client
    NODE_VERSION: 5.6.0

  tasks:
    - name: Creates directory
      file: path="{{ APP_PATH }}" state=directory owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"
      sudo: yes
      tags:
        - app-install

    - name: Copy packages
      copy: src="../{{ item }}" dest="{{ APP_PATH }}" owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"
      with_items:
         - chute
         - config.json
         - config.py
         - makefile
         - manage.py
         - README.md
         - requirements.txt
         - run.py
      tags:
        - app-install

    - name: Install packages
      pip: path="{{ APP_PATH }}/requirements.txt" virtualenv=chute-client
      tags:
        - app-packages-install
        - app-install

    - name: Setup the cron
      cron: name="Chute - Client" minute="0,30" job=""
      tags:
        - app-cron-install